= Formula Values
:toc:
:sectnums:

== Specification

A Formula Value is a way to specify values for a property in different contexts.

There are three types of Formula Values:

- A formula, which **always** starts with '='.
- A concatenated text, which is **always** wrapped between '{{' and '}}'.
- A simple value, which **never** fits the formats of a formula or a concatenated text.

== Formula

A Formula always starts with '='.

Other properties can be referenced by wrapping their path within '{{}}'.

The available functions for a Formula are:

=== dateDiff

Calculates the difference between two dates with the specified units.
This operation is the equivalent of `<date1>-<date2>`, which will return a positive number when `<date1>` is greater than `<date2>`.

[source,text]
----
dateDiff(<date1>, <date2>, <unit>)
// returns an integer
----

* **<date1>,<date2>** _[string:required]_ A date/datetime/time in the following formats:
** 'YYYY-MM-DD'
** 'YYYY-MM-DD HH:mm:ss'
** 'HH:mm:ss'

* **<unit>** _[string:optional]_ The unit to calculate the difference between dates/datetimes/times.
When not specified, its default value is "seconds".
Available units are:
** "years" or "Y"
** "months" or "M"
** "weeks" or "W"
** "days" or "D"
** "hours" or "h"
** "minutes" or "m"
** "seconds" or "s"

=== datetimeFromNow

Calculates a new datetime from now.

[source,text]
----
datetimeFromNow(<year>,<month>,<day>,<hour>,<minute>,<second>);
// returns an ISO formatted date as a string.
----

* **<year>** _[number:optional]_ A delta to modify the year of the current date.
If it's positive, the current year will increase.
If it's negative, the current year will decrease.

* **<month>** _[number:optional]_ A delta to modify the month of the current date.
If it's positive, the current month will increase.
If it's negative, the current month will decrease.

* **<day>** _[number:optional]_ A delta to modify the day of the current date.
If it's positive, the current day will increase.
If it's negative, the current day will decrease.

* **<hour>** _[number:optional]_ A delta to modify the hour of the current date.
If it's positive, the current hour will increase.
If it's negative, the current hour will decrease.

* **<minute>** _[number:optional]_ A delta to modify the minute of the current date.
If it's positive, the current minute will increase.
If it's negative, the current minute will decrease.

* **<second>** _[number:optional]_ A delta to modify the second of the current date.
If it's positive, the current second will increase.
If it's negative, the current second will decrease.

=== sum

Calculates the sum of the elements in the provided array.

[source,text]
----
sum(<values_array>);
// returns the sum of all the values as a number.
----

* **<values_array>** _[number[]:required]_ An array of values to be summed.

=== extract

Extracts a substring in the provided 0-based `<index>` by splitting the given string `<value>` with a `<separator>`.

[source,text]
----
extract(<value>,<separator>,<index>)
// returns a string
----

* **<value>** _[string:required]_ A string used as base to perform the splitting and extraction.

* **<separator>** _[string:required]_ A string used to split the provided value.

* **<index>** _[number:optional]_ The index of the element to be retrieved in the value split by the separator.
